### ISSUE TITLE
Global Area Support

### ISSUE THREAD

**Issue by yulianglukhenko** [infinitered/thesis-phoenix#15]
With Concrete5, we had the ability to define a `GlobalArea` vs a `PageArea`. With global areas, you would edit the content once, and it would propagate the changes to all pages that used it. A nice to have.

@jamonholmgren

**Comment by jamonholmgren** [comment]
Agree. API could look something like this:

```elixir
<%= content(:global, "Footer Contact Info", :html) do %>
  <a href="mailto:jamon@example.com">jamon@example.com</a>
<% end %>
```

What do you think, @yulianglukhenko ?

**Comment by yulianglukhenko** [comment]
Yes, I like that. So, what if someone was to add a page area with the same name? What would happen?

**Comment by jamonholmgren** [comment]
It would be fine, because the names are namespaced behind the page slug and/or `global`, so it would be essentially:

```
ID Page      Name
1  "/"       "Area"
2  "global"  "Area"
```

**Comment by yulianglukhenko** [comment]
![](https://s-media-cache-ak0.pinimg.com/564x/99/8e/b9/998eb9ab1e0912e40ba1ad875eb7675d.jpg)

@jamonholmgren

**Comment by jamonholmgren** [comment]
We went with this API, to reduce overloading those functions too much:

```eex
<%= global_content(@conn, "Footer Text", :html) do %>
  <h4>Contact Info</h4>
  <ul>
    <li>Call us at (800) 555-1212</li>
    <li>Email us at hello@example.com.</li>
  </ul>
<% end %>
```
