### ISSUE TITLE
Don't output markup if content blank && no default content set.

### ISSUE THREAD

**Issue by yulianglukhenko** [infinitered/thesis-phoenix#18]
It would be awesome if a content area wouldn't output the thesis markup after being published if the contents are blank. They can reappear in edit mode. Here's an example where that would be useful: 

![](http://d.pr/i/1kEW8+)

**Comment by yulianglukhenko** [comment]
I'm sure someone could use the html content area and add a div inside styled like this, but it's not practical to expect clients to write HTML.

**Comment by yulianglukhenko** [comment]
@jamonholmgren

**Comment by jamonholmgren** [comment]
Good idea.

**Comment by jamonholmgren** [comment]
Added in #26 -- now outputs `thesis-content-empty` if empty.
