### ISSUE TITLE
Allow people to add tags to a content area

### ISSUE THREAD

**Issue by yulianglukhenko** [infinitered/thesis-phoenix#19]
A cool feature would be to allow people to tag a content area and open up those tags for the dev to use to alter added content. 

A couple examples:

You have a text content area to output an alert on the page. The dev would add the following to the content area: `tags: %{type: :single, items: ["danger", "warning", "info"]}`. There would be some kind of intuitive way of displaying them on the front-end for users to select (in this case only one option). After the users make a selection, in this case, the dev could ouput the selected tag as a className on the div (to change background color with css).

Another example would be for image alignment: `tags: %{type: :single, items: ["center", "center top", "center bottom"]}`. The dev would then output the selection as an inline style on the div. 

As for a different case for the type: `%{type: :multiple, items: ["one-bedroom", "two-bedroom", "one-bath", "two-bath", "single-story", "two-story"]`. This would allow the user to select more than one tag, in the case that the dev is building a filter. 

@jamonholmgren

**Comment by jamonholmgren** [comment]
I could see this being a custom content block. I'm still figuring out how custom content blocks might work with Thesis, but that's my thought.

**Comment by jamonholmgren** [comment]
Fixed in #26 with the `raw_html` content type.
