### ISSUE TITLE
Thesis fails to save content if page description length is > 255

### ISSUE THREAD

**Issue by yulianglukhenko** [infinitered/thesis-phoenix#31]
![](http://d.pr/i/15WmG+)

I tried editing a content area, but it would not save because the page description exceeded the allowed char length. I think the field type for page description should be `text`. Thesis isn't made to enforce SEO best-practices and it would be a bummer if a client tried adding a really long page description and it would fail. 

In my case, this was a client-provided default page description to be used on all pages. 

@jamonholmgren

**Comment by jamonholmgren** [comment]
We _could_ enforce the 255 char length limit and just provide a friendlier error message.
