### ISSUE TITLE
Ability to create, edit, delete new dynamically routed pages

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/thesis-phoenix#37]
With the new tray, we should more easily be able to create, edit, and delete dynamically routed pages. I'd like to tackle this next.

**Comment by yulianglukhenko** [comment]
We also have 2 page related buttons ready to go. What fields do you plan on having?  Because if it's only Meta, then the tray with the buttons is all ready. Just needs to be hooked up.

**Comment by jamonholmgren** [comment]
Yeah, it's more about the routing and template selection part.

**Comment by jamonholmgren** [comment]
So, here are some things I'm learning as I explore this a bit:

1. We can tell the dev to route a wildcard (`get "/*path", PageController, :dynamic`) pretty easily.
2. If the page doesn't exist in the database, we should probably render a 404...or leave that up to them?
3. Showing different templates should be fairly easy. I'm thinking we have the dev tell us what view to use, and then we just pull all templates using `<ViewName>.__templates__/0`. Then we render the proper one, based on what is in the database, or a default.

Maybe some sort of helper would be useful for rendering this.

```elixir
# router.ex

  get "/*path", IrWebsite.PageController, :dynamic

# page_controller.ex

  def dynamic(conn, _params) do
    Thesis.Controller.render_dynamic(conn, PageView, default: "index.html")
  end
```

I got some exploratory code partially done in the `feature/dynamic-routing` branch.

**Comment by jamonholmgren** [comment]
For #3, I'm realizing that it's not quite that easy. For one thing, creating new pages requires that we know in advance what the template options might be -- but we only retrieve those if the _current_ page was dynamically generated, which it very well may not be (and the first created dynamic page certainly won't be).

Instead, we _could_ leave the template selection in the hands of the host app developer, perhaps through a config. This would be easier to retrieve for displaying in the AddPage tray.

I'll do some exploratory code there too. I've also refined the API a bit:

```elixir
# router.ex

  get "/*path", IrWebsite.PageController, :dynamic

# page_controller.ex

  def dynamic(conn, _params) do
    conn
    |> render_dynamic(default: "index.html", not_found: MyApp.ErrorView)
  end
```

**Comment by jamonholmgren** [comment]
Ref #42
