### ISSUE TITLE
Template Options and Page Delete Button present on non-dynamic page.

### ISSUE THREAD

**Issue by yulianglukhenko** [infinitered/thesis-phoenix#49]
When editing the page settings on a non-dynamic page (e.g. home page), the template options, page path, and redirect input field are all present.

![](http://infinitered.d.pr/1cZt3+)

After clicking "Save", the delete button appears on the non-dynamic page. 

![](http://infinitered.d.pr/11t74+)

---

These options should not before there. 

Here's an example of where this is disastrous as of right now. I have a non-dynamic page. I make changes to it. I tweak the meta info (page all of a sudden becomes 'dynamic' and delete button appears). I click on the delete button. The page doesn't actually get deleted, but it resets ALL of the content.

Pretty major bug. 

---

A proposed solution is not to repurpose the page settings tray. Create another tray with its own handlers that's called dynamic page tray. 

@jamonholmgren

**Comment by jamonholmgren** [comment]
This should be fixable without creating a whole new tray. I'll look into it tonight @yulianglukhenko .

**Comment by yulianglukhenko** [comment]
Ok.. I'm just thinking of ways to keep this clean and future proof; but, up to you.

**Comment by jamonholmgren** [comment]
Yeah, I'll keep that in mind looking at it. Right now, making new trays is kind of a PITA, because we have to duplicate so much of the JSX.

**Comment by jamonholmgren** [comment]
Confirmed issue, working on this @yulianglukhenko .
