### ISSUE TITLE
Raw HTML editor block is too short

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/thesis-phoenix#50]
![image](https://cloud.githubusercontent.com/assets/1479215/18256993/b2cb5b4a-7371-11e6-9193-e9467f23df38.png)

Should be taller.

**Comment by yulianglukhenko** [comment]
@jamonholmgren it was fine until "someone" made the textarea block self closing:

![](http://infinitered.d.pr/1dWPJ+)

**Comment by jamonholmgren** [comment]
@yulianglukhenko I wonder if my helpful linter did that. Someone can fix it pretty easily then.

**Comment by manusajith** [comment]
@jamonholmgren tried to take a stab at this, but reverting the change that @yulianglukhenko mentioned didn't seem to fix the issue.

**Comment by yulianglukhenko** [comment]
@manusajith @jamonholmgren hmm. must be something else then. I'm going to see what this looks like on one of my projects after I upgrade. 

On a side note, textareas should still have a closing tag :) It'll still function as expected, just won't validate. I'm not sure if that's a feature of jsx to convert them...

**Comment by yulianglukhenko** [comment]
@jamonholmgren @manusajith alright guys.. im quick to blame jamon so i'm sorry (not really). The textarea should have a `min-height` of probably `200px` added to the `_forms.sass`. It has been looking fine everywhere for me because I work on thesis on projects that already have form styles (and textarea min-heights).

**Comment by jamonholmgren** [comment]
![2016-09-08-4vwb4](https://cloud.githubusercontent.com/assets/1479215/18374629/84eea2ec-7603-11e6-9992-41846d6eb605.png)

Perfect.

**Comment by yulianglukhenko** [comment]
@jamonholmgren @manusajith looks like the sass wasn't compiled in the PR. I'll submit the compiled version along with a few tweaks later on today.
