### ISSUE TITLE
Two content blocks with the same name causes undesirable behavior

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/thesis-phoenix#60]
If an app developer copies & pastes a content block and forgets to change the name, Thesis will update both with the last-in content.

Proposed solution: detect this scenario in Javascript and display an alert to the user. Should be relatively straightforward to implement.

@yulianglukhenko @darinwilson

**Comment by yulianglukhenko** [comment]
Could this be detected with Elixir instead? This way we could prevent an "update" if theres a duplicate block. Probably would be cleaner with Elixir than adding more logic to JS.

**Comment by jamonholmgren** [comment]
@yulianglukhenko It can't, unfortunately. We learn about new content blocks for the first time in the template, at which point it's too late to start modifying the `@conn` struct. This will be much better as a JS warning.
