### ISSUE TITLE
Reorder editor buttons

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/thesis-phoenix#64]
Currently, the order goes like this:

* Save
* Page settings
* Cancel
* Add page
* Delete page
* Toggle edit

![image](https://cloud.githubusercontent.com/assets/1479215/18611869/aef8b9c8-7cfd-11e6-84df-5f7be934cbce.png)

I think this makes more sense from a UX standpoint:

* Add page
* Delete page
* Page settings
* Save
* Cancel
* Toggle edit

After using it for a while, I also dislike hover displaying Add and Delete buttons. I think those should only display on click. It feels like there are two "modes" and it's not clear why.

cc @yulianglukhenko

**Comment by jamonholmgren** [comment]
@yulianglukhenko Okay, I can probably get on board with that idea. But let's get @justinhuskey's viewpoint on this, to be sure.

**Comment by justinhuskey** [comment]
More common to do the two states like Yulian mentioned. 

If the user is editing a page, don't distract them with anything that isn't implied with the action: edit a page. 

I see new and delete as more top level, and then save and cancel as secondary edit features. 

Although, is save the right word? Something like "save" wouldn't make me think my changes are live. A label like "Publish" would give it more weight, and help manage expectations.

I'd use save if there's version history. Like "Save a Version".

**Comment by jamonholmgren** [comment]
OK, the designer has spoken. I like "Publish" or "Publish Changes" too.

**Comment by yulianglukhenko** [comment]
@jamonholmgren i'll have to fix this later this week. it's not really an "easy" fix. i was learning animations when doing this so the code isn't the best and it's very hard to work with. I opened up an issue to rework the buttons (issue #69)

**Comment by jamonholmgren** [comment]
Okay, thanks @yulianglukhenko .
