### ISSUE TITLE
Intermittent duplicate content rows

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/thesis-phoenix#83]
As reported by @yulolimum, we've run into an intermittent issue where sometimes duplicate rows are created. It's been a real bear to replicate locally. Until we are able to fix this, I'm going to push an update that is more vigorous about checking for duplicates before creating new content rows.

Add more info here as we find any.

**Comment by yulolimum** [comment]
This was addressed a few version ago. Keeping this open if people run into this again.
