### ISSUE TITLE
Content Transfer Feature

### ISSUE THREAD

**Issue by yulolimum** [infinitered/thesis-phoenix#89]
I ran into this doing the Infinite Red Ignite page. All of the content was done on staging and after deployment, we either had to manually copy paste to production or transfer the db records through navicat. 

What would be cool is if there was an `Content Export/Import` button in the thesis tools. Clicking that would open up the side tray where you would see a export textarea prefilled with serialized data for this page in a format that thesis could recognize when importing. The tray would also have an import textarea where you would paste the data. You could then Apply to import the data (this would change the content on the page). You could then Save. 

As far as Thesis Images go, they could be just passed as URLs pointing to the staging with a query string. Thesis would recognize that query string and import them by downloading. 

Seems like a very very straightforward task. 

Thoughts?

**Comment by jamonholmgren** [comment]
Agree, this would be very valuable.

**Comment by jamonholmgren** [comment]
@yulolimum I'm thinking we wouldn't actually save the content when the user pasted it into the import box. Instead, we'd apply it to the whole page with JS so they could preview it before clicking save.

**Comment by yulolimum** [comment]
>You could then Apply to import the data (this would change the content on the page). You could then Save.
